### ISSUE TITLE
/cloud/install-cli/ Page not found

### ISSUE THREAD

**Issue by MatrixManAtYrService** [astronomer/docs#396] opened 2022-02-21 03:42 UTC
I searched for "astrocloud cli", first link brought me here: https://docs.astronomer.io/cloud/install-cli/
it 404's

<img width="1115" alt="Screen Shot 2022-02-20 at 8 40 08 PM" src="https://user-images.githubusercontent.com/5834582/154885455-32a67c73-9bfe-4140-8a17-6b48ae185fbd.png">

**Comment by paolaperaza** [comment] 2022-02-21 20:56
Thanks for the catch here, @MatrixManAtYrService. Looks like @astrorfox fixed this one today, and I just confirmed - closing out 😊

**Closed by paolaperaza** 2022-02-21 20:56 UTC
