### ISSUE TITLE
System Viewer doesn't have access to list all the workspaces in astronomer Software Cluster

### ISSUE THREAD

**Issue by ishitamishra13111999** [astronomer/docs#2665] opened 2023-08-08 11:38 UTC
https://github.com/astronomer/docs/blob/442083ffbf38aec5ae9e42d826213c532ef95b51/software_configs/0.30/default.yaml#L433

In astro v0.30.5

Not able to get the workspace list in any astro cluster using the **_system viewer_** api token. It return a empty list even if workspaces exist in the astronomer software cluster

Running the workspace listing GQL with system viewer api token
`query workspaces {
workspaces {
id
label
}}
`

Response :
`
{
"data": {
"workspaces": []
}
}
`

https://github.com/astronomer/docs/blob/442083ffbf38aec5ae9e42d826213c532ef95b51/software_configs/0.30/default.yaml#L426  

We are seeing the same issue when trying to get the deployments in a workspace  using the **_system viewer_** api token. It return a empty list even if deployments exist in the astronomer workspace.

`query workspaces {
workspace (workspaceUuid: "clju94d09717714hg16oc6o7w") {
id
label
deployments {id}
}}
`

Response :
`
{
"data": {
"workspace": {
"id": "clju94d09717714hg16oc6o7w",
"label": "bfdaf-bfdishita22",
"deployments": []
}
}
}
`

**Comment by ishitamishra13111999** [comment] 2023-08-08 11:39
@jwitz

**Comment by Simpcyclassy** [comment] 2023-08-09 12:09
This is not a bug actually. The `workspaces` query returns only workspaces the user belongs to as this is a workspace-level query. To get all workspaces at the system level you need to query `sysWorkspaces`

**Comment by jwitz** [comment] 2023-08-14 14:19
Hi @ishitamishra13111999 I'm going to close this issue out because of Chioma's comment. It seems like this won't require a documentation update, though it would be good for us to add System-level examples in the Houston API documentation.

**Closed by jwitz** 2023-08-14 14:19 UTC
