### ISSUE TITLE
Acadmey page throwing 403

### ISSUE THREAD

**Issue by vatsrahul1001** [astronomer/docs#3953] opened 2024-07-19 10:13 UTC
Hi Team, One of our test which make request call to `<https://academy.astronomer.io/>` and check its status code started throwing 403 recently. Can someone check this out

[Slack Message](https://astronomer.slack.com/archives/C015V2JFKT5/p1721383713165039?thread_ts=1721383713.165039&cid=C015V2JFKT5)

**Comment by katiebrady-astro** [comment] 2024-07-19 13:02
Hey @vatsrahul1001, thanks for the heads up! Looks like this was caused by a tag we no longer use returning a 403. Tag has been removed and issue should be cleared up now! ✅

**Comment by lzdanski** [comment] 2024-07-29 19:42
Slack conversation shows this is resolved. Closing.

**Closed by lzdanski** 2024-07-29 19:42 UTC
