### ISSUE TITLE
Enhance `Run your first DAG` with 3 ways to deploy

### ISSUE THREAD

**Issue by paolaperaza** [astronomer/docs#2338] opened 2023-05-25 17:34 UTC
### Context

We link to `Run your first DAG` doc in the Cloud UI, but I was talking to @nicholasfilippi and realizing that we don't tell users about ALL of the ways they can deploy DAGs. With Hosted Trials, it's becoming very obvious that it's easy to create a Deployment... and then people don't know what to do from there.

We can still focus on Astro CLI method, but for someone learning our product we should be clear that they can also deploy DAGs via CI/CD and Astro Cloud IDE, and then direct them that way.

### Ask

In this doc: https://docs.astronomer.io/astro/create-first-DAG

Let's update the overview to add:
- A new H3 (not sure what we call it) that (very briefly -- 1 sentence) breaks down the 3 ways you can deploy DAGs to Astro
- Basic attribute for each (e.g. Astro CLI = `fastest`, Astro Cloud IDE = `for non Airflow or Python users`, CI/CD = `For teams that already use CI/CD tool` or something like that)
- It'd be cool to have a visual in here

Might have to discuss this @jwitz + @lzdanski but wanted to add an issue

**Comment by jwitz** [comment] 2023-06-02 12:28
Thinking through.. if the problem is "and then people don't know what to do from there", how would presenting another choice at the beginning of the article help them get through that problem? Neither the Cloud IDE nor CI/CD are particularly intuitive ways to get DAGs onto Astro if you're just starting out and want to see if it works.

To me this seems more like a product issue. After you create a Deployment, there's nothing in the way of "getting started" content to guide you to the next step. All you get is this:

<img width="1170" alt="Screenshot 2023-06-02 at 1 27 14 PM" src="https://github.com/astronomer/docs/assets/74574233/3ca13619-3d7e-4fa5-a16d-bd3e9013c774">

Even if there was content in this doc, there's nowhere in the product to send you there after you create a Deployment.

**Comment by jwitz** [comment] 2023-06-02 12:30
@nicholasfilippi Are there any current efforts to introduce help content to a Deployment page with no deploys? Maybe we can collaborate on the text/ experience there.

**Comment by jwitz** [comment] 2023-07-05 09:39
Closing this out for now, not sure updating the doc with more options the right way to address this issue.

**Closed by jwitz** 2023-07-05 09:39 UTC
Labels: product/astro, kind/enhancement
