### ISSUE TITLE
Access Airflow Database doc needs an audit/ renovation

### ISSUE THREAD

**Issue by jwitz** [astronomer/docs#240] opened 2021-12-17 17:40 UTC
@jwitz commented on [Thu Jan 28 2021](https://github.com/astronomer/docs-archived/issues/232)

## What kind of documentation change are you requesting?

* **Significant change to an existing document**: Add the `enhancement` label to this issue. 
  
### For new documents and enhancements, answer the following questions**

_What is the purpose of the document/enhancement? Select all that apply:_
- [ ] Setup steps for a new feature for an upcoming release (Add the appropriate version label to this issue). 
- [X] Information for an existing feature that isn't yet documented.
- [ ] Additional considerations/ reference material for an existing feature or document.

#### _Describe the problem/ feature that requires documentation:_ 

Based on our website traffic, [Access the Airflow Database](https://www.astronomer.io/docs/cloud/stable/customize-airflow/access-airflow-database) is one of our most popular docs on the site. Unfortunately, we haven't yet made style/ formatting updates to this guide based on our latest changes to Astronomer's style. 
  
#### _Describe what should be included in the document, making sure to outline what users should be able to achieve with the doc. In addition, include links to any relevant existing documentation, support tickets, messages, or external content:_
 
We should perform an audit/ renovation of the guide, making sure to make steps as clear and concise as possible and link out to other docs where possible.

**Comment by paolaperaza** [comment] 2021-12-28 18:49
Duplicate of #181 - closing out

**Closed by paolaperaza** 2021-12-28 18:49 UTC
Labels: product/enterprise
