### ISSUE TITLE
Missing AC Versions

### ISSUE THREAD

**Issue by kaxil** [astronomer/docs#453] opened 2021-09-09 12:16 UTC
**Affected Document:**
  
https://www.astronomer.io/downloads/ does not contain AC 2.1.3 which was released on 2021-08-23 - https://github.com/astronomer/ap-airflow/blob/master/2.1.3/CHANGELOG.md#astronomer-certified-213-1-2021-08-23

**Severity:**

- [x] Critical: This document has incorrect or missing information. Add the `error/critical` label to this issue.
- [ ] FYI: The document is misleading or could benefit from additional context or guidance. Add the `error/FYI` label to this issue.
- [ ] Typo: Add the `error/typo` label to this issue.
  
**Suggested Change (include links to relevant existing docs, support tickets, messages, or external content):**

**Additional Notes:**

**Comment by jwitz** [comment] 2021-09-09 14:06
Closing this out as a duplicate of https://github.com/astronomer/issues/issues/3407. Our downloads page is based elsewhere on our site and should be handled by @medinab or another front end developer

**Closed by jwitz** 2021-09-09 14:06 UTC
