### ISSUE TITLE
Software chart versions matrix

### ISSUE THREAD

**Issue by rwalshe** [astronomer/docs#3192] opened 2023-12-15 18:59 UTC
### Issue Type

Inaccurate, misleading, or out-of-date information

### Links to Affected Docs

https://docs.astronomer.io/software

### The Issue or Context

Customers often ask for the chart versions associated to a Software version.  

For example, "could you confirm the Airflow chart version for 0.33.2?"

To find this, a user currently needs to know to go to the following location in our public repo - 

https://github.com/astronomer/astronomer/blob/v0.33.2/charts/astronomer/values.yaml

airflowChartVersion: 1.9.5

### Fix or Proposed Change

Having the chart version indicated in a matrix in the software docs would be helpful for customers to self-determine the chart version associated to a Software version

**Comment by jwitz** [comment] 2023-12-29 13:11
Duplicate of https://github.com/astronomer/docs/issues/3222

**Closed** 2024-01-11 11:33 UTC
Labels: product/software
