### ISSUE TITLE
Multiple Python version support in Astro Runtime

### ISSUE THREAD

**Issue by jedcunningham** [astronomer/docs#2417] opened 2023-06-12 22:40 UTC
### New Feature Description

Starting with ~~8.5.0, Astro Runtime 8.5+~~ TBD will have support for multiple python versions: 3.8, 3.9, and 3.10 (the default).

This allows customers to opt-in to another python version if it better suits their needs.

The existing tags we all know and love aren't changing - keep using `8.5.0` which will give you 3.10!

However, you now have tags like `8.5.0-python-3.8` or `8.5.0-python-3.9-base` available to you.

### Required Reviewers

@paolaperaza @cmarteepants

### Links to Internal Info or Resources

https://astronomer.slack.com/archives/C026XPSJ0JK/p1686603494744609

### Release date

~~Likely 6/15/2024~~ TBD

**Comment by jwitz** [comment] 2023-07-27 11:41
Closing as duplicate of https://github.com/astronomer/docs/issues/2614

**Closed by jwitz** 2023-07-27 11:41 UTC
Labels: product/astro, new-feature
