### ISSUE TITLE
Update Feature Overview for Astro

### ISSUE THREAD

**Issue by paolaperaza** [astronomer/docs#1050] opened 2022-08-19 16:46 UTC
This doc is an overview of our Astro product offering and is out-of-date: https://docs.astronomer.io/astro

We need to:

- [ ] Add data lineage to our explanation of observability
- [ ] Consider combining Astro Runtime with timely releases of Airflow
- [ ] Add worker queues to line on worker autoscaling
- [ ] Add any other RBAC detail to existing line

I'll take care of this one -- just adding here as a reminder ✅

**Comment by jwitz** [comment] 2022-09-26 10:34
@paolaperaza Should we close this out given plans for the landing page?

**Comment by jwitz** [comment] 2022-10-19 13:24
Closing as duplicate of https://github.com/astronomer/docs/issues/1359

**Closed by jwitz** 2022-10-19 13:24 UTC
Labels: error/misleading, product/astro
